### ISSUE TITLE
Is basic documentation available?

### ISSUE THREAD

**Issue by jpcartailler** [gr8lawrence/ARTDeConv#1]
Greetings and thank you for putting this together. After perusing your paper, we would like to try out this tool but couldn't find any documentation about its usage. Is any forthcoming? Cheers!

**Comment by gr8lawrence** [comment]
Hi, thank you for the interest in trying it out! Yes, since the preprint is out our next step is to tidy up this repository and make the package documentation ready. It will likely happen in January. I will keep you updated!

**Comment by gr8lawrence** [comment]
Hi @jpcartailler, I have updated the basic documentation in the README file, and attached a toy data to the package based on the pre-print Section 3.2. Let me know if you have any comments or encounter any further issues.
